### ISSUE TITLE
Bloodhound not working

### ISSUE THREAD

**Issue by iNoSec2** [ShutdownRepo/Exegol#72] opened 2022-01-21 22:19 UTC
Hello,
Before complaining xD thanks for the awesome work!!!
I cant run bloodhound with `exegol start -e bloodhound` or even directly in the docker or the daemon it seems it isnt installed anymore in /opt
My choice was the AD docker image so it must be here, neo4j work but when i type `bloodhound` i have `zsh: no such file or directory: /opt/tools/BloodHound4/BloodHound-linux-x64/BloodHound`

Nothing i cant resolve but let you know because it seems to not be "normal".

Exegol is awesome!!!

**Comment by ShutdownRepo** [comment] 2022-01-22 08:58
Hey there! Thank you for raising this issue! 
Can you please run `exegol version` on your host and `cat /opt/.exegol_version` in the container you are attempting the execution of bloodhound on?

**Comment by ShutdownRepo** [comment] 2022-01-22 14:31
If you're running with the `ad` image, then my bad, bloodhound is currently missing in this image
I will fix this as soin as I get back to a computer

**Comment by iNoSec2** [comment] 2022-01-22 19:37
Thanks a lot for all you do!! Im not on my PC until tomorrow but it was the latest version and like you said i run the `ad` image 😀
Your project is awesome, i only use exegol for every redteam i do since i discover 1 month ago!!!

**Comment by ShutdownRepo** [comment] 2022-01-23 14:20
The issue should be fixed. I added the installation of GUI tools to the `ad` image. It includes BloodHound. I tested it on my side and it works. I am closing this issue but feel free to reopen it if you feel like the problem is still there! My bad for not having BloodHound in the `ad` image in the first place, it's a must have, and this slipped through since I mostly use the `dev` and `stable` images.

**Closed by ShutdownRepo** 2022-01-23 14:20 UTC
