### ISSUE TITLE
Container is not running

### ISSUE THREAD

**Issue by 0zes** [ShutdownRepo/Exegol#120] opened 2022-10-24 12:22 UTC
Hi, i'm trying to install exegol but when i try to launch a session it tells me that the container is not running. I don't know what to do.

```ubuntu@ubuntu-instance:~$ exegol start cours -vvv
[*] Exegol is currently in version v4.0.5
[D] Pip installation: On ✔                                                                                                                                                                                         
[D] Git source installation: Off 🪓                                                                                                                                                                                
[D] Host OS: Linux                                                                                                                                                                                                 
[D] Arch: aarch64                                                                                                                                                                                                  
[D] Docker desktop: Off 🪓                                                                                                                                                                                         
[D] Shell type: Linux                                                                                                                                                                                              
[D] Last update check: 24/10/2022                                                                                                                                                                                  

[+] Exegol thanks Capgemini for supporting the project (dev contributors) 🙏                                                                                                                                       
[+] Interested in joining Capgemini? https://www.capgemini.com/fr-fr/carrieres/offres-emploi/                                                                                                                      
[*] Starting exegol                                                                                                                                                                                                
[*] Arguments supplied with the command, skipping interactive mode                                                                                                                                                 
[D] Attribute not found in parameters: multicontainertag                                                                                                                                                           
[D] == Loading container : exegol-cours                                                                                                                                                                            
[D] Parsing envs : DISPLAY=:0                                                                                                                                                                                      
[D] Adding env DISPLAY=:0                                                                                                                                                                                          
[D] Parsing envs : _JAVA_AWT_WM_NONREPARENTING=1                                                                                                                                                                   
[D] Adding env _JAVA_AWT_WM_NONREPARENTING=1                                                                                                                                                                       
[D] Parsing envs : QT_X11_NO_MITSHM=1                                                                                                                                                                              
[D] Adding env QT_X11_NO_MITSHM=1                                                                                                                                                                                  
[D] Parsing envs : PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                               
[D] Adding env PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin                                                                                                                                   
[D] Capabilities : []                                                                                                                                                                                              
[D] Load devices : []                                                                                                                                                                                              
[D] Parsing mount : {'Type': 'bind', 'Source': '/home/ubuntu/.exegol/workspaces/cours', 'Destination': '/workspace', 'Mode': '', 'RW': True, 'Propagation': 'rprivate'}                                            
[D] Loading workspace volume source : /home/ubuntu/.exegol/workspaces/cours                                                                                                                                        
[D] Private workspace detected                                                                                                                                                                                     
[D] Parsing mount : {'Type': 'bind', 'Source': '/tmp/.X11-unix', 'Destination': '/tmp/.X11-unix', 'Mode': '', 'RW': True, 'Propagation': 'rprivate'}                                                               
[D] Parsing mount : {'Type': 'bind', 'Source': '/etc/timezone', 'Destination': '/etc/timezone', 'Mode': '', 'RW': False, 'Propagation': 'rprivate'}                                                                
[D] Parsing mount : {'Type': 'bind', 'Source': '/etc/localtime', 'Destination': '/etc/localtime', 'Mode': '', 'RW': False, 'Propagation': 'rprivate'}                                                              
[D] Parsing mount : {'Type': 'bind', 'Source': '/home/ubuntu/.exegol/my-resources', 'Destination': '/my-resources', 'Mode': '', 'RW': True, 'Propagation': 'rprivate'}                                             
[D] Parsing mount : {'Type': 'bind', 'Source': '/home/ubuntu/.exegol/exegol-resources', 'Destination': '/opt/resources', 'Mode': '', 'RW': True, 'Propagation': 'rprivate'}                                        
[D] Try to retrieve image version from labels                                                                                                                                                                      
[D] └── nightly → (remote) sha256:26309b5f992aa96c1be310ef492f9a5b5f953a1ee549437212713ee42327a12b                                                                                                                 
[*] Starting container cours                                                                                                                                                                                       
[D] Adding xhost ACL to local:exegol-cours                                                                                                                                                                         
[*] Location of the exegol workspace on the host : /home/ubuntu/.exegol/workspaces/cours                                                                                                                           
[+] Opening shell in Exegol 'cours'                                                                                                                                                                                
[D] Opening shell with: docker exec -ti 8c588cd520783f21f0725d85ff018c159444e9035c3d24b5cc7abff1d96e5f99 zsh                                                                                                       
Error response from daemon: Container 8c588cd520783f21f0725d85ff018c159444e9035c3d24b5cc7abff1d96e5f99 is not running
```

**Comment by ShutdownRepo** [comment] 2022-10-24 12:25
Hi, can you share the command you used?

**Comment by ShutdownRepo** [comment] 2022-10-24 12:46
Okay that's in fact some weird behavior. Did you try restarting your Docker service and/or computer?

**Comment by ShutdownRepo** [comment] 2022-10-24 12:57
Could be, can you reach me at Shutdown#2539 on Discord? We'll try to debug this live

**Comment by 0zes** [comment] 2022-10-24 13:07
Added you on Discord

**Comment by ShutdownRepo** [comment] 2022-10-24 14:24
After some debugging, it seems the issue is due to the fact exegol is running on an ARM64 (aarch64) oracle cloud instance. The multi-arch support is still in development. Including @0zes in the beta testing program to see if this was in fact the problem.

**Comment by ShutdownRepo** [comment] 2022-10-24 17:24
Closing this issue. It was fixed by using the multi-arch support that will be released in a few weeks (yeah 🎉)

**Closed by ShutdownRepo** 2022-10-24 17:24 UTC
Labels: bug, multi-arch
