### ISSUE TITLE
Share timezone

### ISSUE THREAD

**Issue by naacbin** [ShutdownRepo/Exegol#86] opened 2022-05-01 14:52 UTC
On arch by default the file `/etc/timezone` doesn't exist. I would except to have the container mounting `/etc/localtime` instead, however I get the following error :

```bash
[V] Config: Enabling host timezones
[-] Unable to create the volume folder on the filesystem locally.
[!] Insufficient permissions to create the folder: /etc/timezone 
```

Having a try/catch would be sufficient I supposed to fix this problem.
`exegol/model/ContainerConfig.py` line 269 currently look like following
```python
if not self.__share_timezone:
    self.__share_timezone = True
    logger.verbose("Config: Enabling host timezones")
    self.addVolume("/etc/timezone", "/etc/timezone", read_only=True)
    self.addVolume("/etc/localtime", "/etc/localtime", read_only=True)
```

**Comment by naacbin** [comment] 2022-05-01 15:13
After some testing having a try/catch may not be a solution.
The problem come from line 571, `logger.critical` stop the app. A fix would be to change `logger.critical` to `logger.error` and exit function (with a return for example). 

What I did to "fix":
```python
if volume_type == 'bind' and not host_path.startswith("\\\\"):
    try:
        os.makedirs(host_path, exist_ok=True)
    except PermissionError:
        logger.error("Unable to create the volume folder on the filesystem locally.")
        logger.error(f"Insufficient permissions to create the folder: {host_path}")
        return 0
    except FileExistsError:
        # The volume targets a file that already exists on the file system
        pass
mount = Mount(container_path, host_path, read_only=read_only, type=volume_type)
self.__mounts.append(mount)
```

**Comment by Dramelac** [comment] 2022-05-01 15:29
Hi, thanks for the feedback!
Indeed this situation had not been foreseen.
The critical behavior with the program exit is however intended in case the volume is manually specified by the user via CLI.

Don't worry, I'll handle it

**Comment by Dramelac** [comment] 2022-05-01 16:18
Fixed in the **dev** branch, will be included in the next release.
I close the ticket, feel free to test (in the dev branch) and reopen it if the problem is not completely corrected.

**Closed by Dramelac** 2022-05-01 16:18 UTC
Labels: bug

**Comment by ShutdownRepo** [comment] 2022-05-01 16:23
Thanks @Dramelac ! Fyi @naacbin you can test those changes by running `exegol update -v` and then choose `dev` when the program asks to select a git branch for the wrapper source code, or by checking out the dev branch from this repo manually.
